apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-go
  name: http-go
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: http-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-go
    spec:
      containers:
      - image: gasbugs/http-go:v2.0
        name: http-go
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            #httpHeaders:
            #- name: Custom-Header
              #value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http-go
  name: http-go
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-go
  type: LoadBalancer
status:
  loadBalancer: {}
